### ISSUE TITLE
Update Documentation for Zumito Docs

### ISSUE THREAD

**Issue by WilliamAcosta1** [ZumitoTeam/zumito-docs#1]
**Problem Description:**
The current documentation for Zumito Docs lacks detail and does not provide clear instructions on how to create a new project using commands. As a result, it can be challenging for users to navigate the platform and take full advantage of its capabilities.

**Proposed Solution:**
I propose updating the documentation for Zumito Docs to include more detailed instructions, step-by-step guides, and best practices for creating a new project using commands. This update would streamline the project creation process, make it easier for new users to get started, and improve the overall user experience.

**Pros:**

- Clear instructions would make it easier for users to navigate the platform and create new projects.
- Improved documentation could reduce the number of support requests, saving time and resources for the development team.

**Cons:**

- Updating the documentation will require additional time and effort from the development team.

**Comment by fernandomema** [comment]
Done
